// Shared currency symbol map — single source of truth
// Used by settings.ts and analytics.ts

export const CURRENCY_MAP: Record<string, { symbol: string; position: "before" | "after" }> = {
  USD: { symbol: "$", position: "before" },
  EUR: { symbol: "\u20ac", position: "before" },
  GBP: { symbol: "\u00a3", position: "before" },
  SEK: { symbol: "kr", position: "after" },
  NOK: { symbol: "kr", position: "after" },
  DKK: { symbol: "kr", position: "after" },
  ISK: { symbol: "kr", position: "after" },
  CZK: { symbol: "K\u010d", position: "after" },
  HUF: { symbol: "Ft", position: "after" },
  PLN: { symbol: "z\u0142", position: "after" },
  RON: { symbol: "lei", position: "after" },
  JPY: { symbol: "\u00a5", position: "before" },
  CNY: { symbol: "\u00a5", position: "before" },
  KRW: { symbol: "\u20a9", position: "before" },
  INR: { symbol: "\u20b9", position: "before" },
  BRL: { symbol: "R$", position: "before" },
  MXN: { symbol: "$", position: "before" },
  AUD: { symbol: "A$", position: "before" },
  CAD: { symbol: "C$", position: "before" },
  CHF: { symbol: "CHF", position: "before" },
  NZD: { symbol: "NZ$", position: "before" },
  SGD: { symbol: "S$", position: "before" },
  HKD: { symbol: "HK$", position: "before" },
  TWD: { symbol: "NT$", position: "before" },
  THB: { symbol: "\u0e3f", position: "before" },
  TRY: { symbol: "\u20ba", position: "before" },
  ZAR: { symbol: "R", position: "before" },
  RUB: { symbol: "\u20bd", position: "after" },
  ILS: { symbol: "\u20aa", position: "before" },
  AED: { symbol: "\u062f.\u0625", position: "before" },
  SAR: { symbol: "\ufdfc", position: "before" },
  PHP: { symbol: "\u20b1", position: "before" },
  MYR: { symbol: "RM", position: "before" },
  IDR: { symbol: "Rp", position: "before" },
  VND: { symbol: "\u20ab", position: "after" },
  ARS: { symbol: "$", position: "before" },
  CLP: { symbol: "$", position: "before" },
  COP: { symbol: "$", position: "before" },
  PEN: { symbol: "S/", position: "before" },
  UAH: { symbol: "\u20b4", position: "before" },
  NGN: { symbol: "\u20a6", position: "before" },
  EGP: { symbol: "E\u00a3", position: "before" },
  PKR: { symbol: "\u20a8", position: "before" },
  BDT: { symbol: "\u09f3", position: "before" },
  QAR: { symbol: "\ufdfc", position: "before" },
  KWD: { symbol: "\u062f.\u0643", position: "before" },
  BHD: { symbol: ".\u062f.\u0628", position: "before" },
  OMR: { symbol: "\ufdfc", position: "before" },
};
